name: Terraform

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: ./terraform/terraform -chdir=terraform init

    - name: Terraform Validate
      run: ./terraform/terraform -chdir=terraform validate

    - name: Terraform Plan
      run: ./terraform/terraform -chdir=terraform plan

    - name: Terraform Apply
      run: ./terraform/terraform -chdir=terraform apply -auto-approve
